# Generated by Django 3.2.23 on 2023-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20231227_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
