# Generated by Django 3.2.23 on 2024-01-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
